import Head from 'next/head'
import { ReactElement } from 'react'
import Features from '../components/landing/Features'
import Footer from '../components/landing/Footer'
import Testimonials from '../components/landing/Testimonials'
import LandingLayout from "../layouts/landing/index"

export default function Home() {

  return (
    <div>
      <Head>
        <title>Main App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-gray-700 bg-white">
        <div className="py-20 hero bg-red-400">
          <div className="container mx-auto px-6">
            <div className="text-4xl font-bold mb-2 text-white">
              Design awesome websites without headaches!
            </div>
            <div className="text-2xl mb-8 text-gray-200">
              A utility-first CSS framework for rapidly building custom designs.
            </div>
            <button className="transform hover:scale-110 transition duration-300 ease-in-out bg-white font-bold rounded-full py-6 px-8 shadow-lg uppercase tracking-wider">
              Get Started
            </button>
          </div>
        </div>


        <Features />

        <Testimonials />

        <section className="call-to-action">
          <div className="container mx-auto px-6 text-center py-10">
            <h2 className="mb-6 text-4xl font-bold text-center text-white">
              Impress them all!
            </h2>
            <h3 className="my-4 text-2xl text-white">
              Build the next generation of design experiences
            </h3>
            <button className="transform hover:scale-110 transition duration-300 ease-in-out bg-white font-bold rounded-full mt-6 py-6 px-8 shadow-lg uppercase tracking-wider">
              Get Started
            </button>
          </div>
        </section>

        <Footer />
      </div>

    </div>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <LandingLayout>
      {page}
    </LandingLayout>
  )
}